# Generated by Django 4.1.6 on 2023-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markshit_app', '0003_student_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
